import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, Archive, Bot, Boxes, ChevronLeft, ChevronRight, CircleDot, Command, Database, GitBranch, LayoutDashboard, LockKeyhole, Pause, Play, RotateCcw, Search, Settings, ShieldCheck, Terminal, Workflow, Wrench, Zap } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { createDemoState, scenarios } from './data/demo'
import type { Agent, AgentStatus, DemoScenario } from './types'
import './styles.css'

const nav = [['Command Center', LayoutDashboard], ['Agents', Bot], ['Trading', Activity], ['Backtests', Workflow], ['Runs', Boxes], ['Artifacts', Archive], ['Repository', GitBranch], ['Memory', Database], ['Settings', Settings]] as const
const teamMeta: Record<Agent['team'], { label: string; icon: typeof Database }> = { 'Research & Data': { label: '01 / INTELLIGENCE', icon: Database }, 'Strategy Lab': { label: '02 / STRATEGY', icon: Zap }, 'Risk & Critic': { label: '03 / GOVERNANCE', icon: ShieldCheck }, 'Build & Execution': { label: '04 / DELIVERY', icon: Wrench } }
const statusTone: Record<AgentStatus, string> = { IDLE: 'idle', QUEUED: 'queued', THINKING: 'thinking', READING: 'reading', USING_TOOL: 'tool', WAITING_DEPENDENCY: 'waiting', REVIEWING: 'reviewing', BLOCKED: 'blocked', FAILED: 'failed', COMPLETED: 'completed' }

function App() {
  const [scenario, setScenario] = useState<DemoScenario>('Normal Run'); const [cursor, setCursor] = useState(4); const [playing, setPlaying] = useState(true); const [collapsed, setCollapsed] = useState(false); const [tab, setTab] = useState('Market'); const [eventFilter, setEventFilter] = useState('All')
  const state = useMemo(() => createDemoState(scenario, cursor), [scenario, cursor]); const active = state.agents.filter(a => ['USING_TOOL', 'THINKING', 'READING', 'REVIEWING'].includes(a.status)).length
  return <div className="app-shell">
    <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}><div className="side-brand"><div className="brand-mark">W</div>{!collapsed && <div><strong>WAWA</strong><small>AGENTIC TRADING</small></div>}<button className="icon-btn collapse" aria-label="Collapse navigation" onClick={() => setCollapsed(!collapsed)}>{collapsed ? <ChevronRight size={16}/> : <ChevronLeft size={16}/>}</button></div><nav>{nav.map(([label, Icon]) => <button key={label} className={label === 'Command Center' ? 'active' : ''} title={label}><Icon size={17}/>{!collapsed && <span>{label}</span>}</button>)}</nav><div className="side-footer">{!collapsed && <><div className="connection-mini"><i className="live-dot"/> <span>SIMULATION</span></div><small>MT5 bridge offline · demo adapter</small></>}</div></aside>
    <main className="main"><header className="command-bar"><div className="eyebrow"><CircleDot size={12}/> COMMAND CENTER <span>/</span> AGENTIC TRADING STATION</div><div className="command-right"><span className="simulation-pill"><i/> SIMULATION</span><span className="repo"><GitBranch size={13}/> main · clean</span><span className="heartbeat">14:37:22 UTC · 42ms</span><button className="palette-btn"><Command size={14}/> Command Palette <kbd>⌘K</kbd></button></div></header>
      <section className="hero"><div><div className="kicker">WAWA OPERATIONS / RUN CONTROL</div><h1>One desk. <em>Four minds.</em><br/>Decisions you can audit.</h1><p>Observe the organization from intake to execution. Every state is derived from a deterministic event stream.</p></div><div className="run-control"><label>DEMO SCENARIO <span>SIMULATION ONLY</span></label><select value={scenario} onChange={e => { setScenario(e.target.value as DemoScenario); setCursor(4) }}>{scenarios.map(s => <option key={s}>{s}</option>)}</select><div className="transport"><button aria-label="Reset run" onClick={() => { setCursor(0); setPlaying(false) }}><RotateCcw size={15}/></button><button className="play" aria-label={playing ? 'Pause' : 'Play'} onClick={() => setPlaying(!playing)}>{playing ? <Pause size={15}/> : <Play size={15}/>}</button><button aria-label="Next event" onClick={() => setCursor(Math.min(4, cursor + 1))}><ChevronRight size={15}/></button><span>{cursor}/4 events</span></div></div></section>
      <section className="stat-strip"><Stat label="ACTIVE AGENTS" value={`${active} / 4`} hint="event-derived" tone="cyan"/><Stat label="RUN STATUS" value={state.run.status} hint={scenario} tone={state.run.status === 'RUNNING' ? 'green' : 'amber'}/><Stat label="RISK GATE" value={state.decision.outcome} hint={`${state.decision.confidence}% confidence`} tone={state.decision.outcome === 'EXECUTE' ? 'green' : 'red'}/><Stat label="MT5 CONNECTION" value="OFFLINE" hint="simulation adapter" tone="muted"/><Stat label="BUILD HEALTH" value={scenario === 'Build Failed' ? 'FAILED' : 'PASSING'} hint="source: demo CI" tone={scenario === 'Build Failed' ? 'red' : 'green'}/></section>
      <div className="workspace-grid"><section className="panel agents-panel"><PanelHeading icon={<Bot size={16}/>} title="Agent organization" meta="4 squads · event synchronized"/><div className="agents-list">{state.agents.map(agent => <AgentCard key={agent.id} agent={agent}/>)}</div></section><section className="panel trading-panel"><PanelHeading icon={<Terminal size={16}/>} title="Trading workspace" meta="DEMO DATA · deterministic feed"/><div className="tabs">{['Market', 'EA Logic', 'Pipeline', 'Backtests', 'Code Changes'].map(t => <button key={t} className={tab === t ? 'selected' : ''} onClick={() => setTab(t)}>{t}</button>)}</div><div className="chart-wrap"><div className="chart-label"><strong>USTEC / M30</strong><span>SIMULATION · no live orders</span></div><svg className="chart" viewBox="0 0 600 210" preserveAspectRatio="none" aria-label="Deterministic demo market chart"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#22D3EE" stopOpacity=".22"/><stop offset="1" stopColor="#22D3EE" stopOpacity="0"/></linearGradient></defs>{[35,75,115,155].map(y => <line key={y} x1="0" x2="600" y1={y} y2={y} stroke="#26344b" strokeDasharray="3 6"/>)}<path d="M0 165 L45 151 L90 158 L135 122 L180 140 L225 104 L270 111 L315 78 L360 96 L405 64 L450 83 L495 52 L540 68 L600 42 L600 210 L0 210Z" fill="url(#area)"/><path d="M0 165 L45 151 L90 158 L135 122 L180 140 L225 104 L270 111 L315 78 L360 96 L405 64 L450 83 L495 52 L540 68 L600 42" fill="none" stroke="#22D3EE" strokeWidth="2"/><circle cx="495" cy="52" r="4" fill="#22D3EE"/></svg><div className="chart-axis"><span>09:00</span><span>12:00</span><span>15:00</span><span>18:00</span></div></div><div className="trade-grid"><Metric label="EA SIGNAL" value="HOLD"/><Metric label="OPEN POSITIONS" value="—"/><Metric label="DRAWDOWN" value="—"/><Metric label="FORECAST / EA" value="—"/></div></section><section className="panel stream-panel"><PanelHeading icon={<Activity size={16}/>} title="Decision stream" meta="live event ledger"/><div className="filter-row">{['All', 'Decisions', 'Tools', 'Errors', 'Reviews'].map(f => <button key={f} className={eventFilter === f ? 'selected' : ''} onClick={() => setEventFilter(f)}>{f}</button>)}</div><div className="event-list">{state.events.filter(e => eventFilter === 'All' || e.eventType === eventFilter.toUpperCase().slice(0, -1)).map(e => <div className={`event ${e.severity}`} key={e.id}><div className="event-marker"/><div><div className="event-top"><b>{e.task}</b><time>{e.timestamp}</time></div><p>{e.summary}</p><small>{e.tool} · {e.progress}% · {e.team}</small></div></div>)}{state.events.length === 0 && <Empty text="Run is ready. Press play to inspect events."/>}</div></section></div>
      <section className="floor panel"><PanelHeading icon={<Workflow size={16}/>} title="Operations floor" meta="event-driven pipeline visualization"/><div className="pipeline">{['Repository / Data Intake', 'Research & Data', 'Strategy Lab', 'Risk & Critic Gate', 'Build & Execution', 'Human Approval'].map((step, i) => <div className={`pipe-step ${i === 3 && state.decision.outcome !== 'EXECUTE' ? 'gate-alert' : ''}`} key={step}><div className="pipe-node">{i === 3 ? <LockKeyhole size={16}/> : i === 5 ? <AlertTriangle size={16}/> : <span>0{i + 1}</span>}</div><strong>{step}</strong>{i < 5 && <div className="pipe-line"><motion.i animate={playing ? { x: [0, 32, 0] } : { x: 0 }} transition={{ duration: 2, repeat: Infinity }} /></div>}</div>)}</div><div className="floor-caption"><span><i className="legend-dot cyan"/> data packet flowing</span><span><i className="legend-dot amber"/> gate requires inspection</span><span><i className="legend-dot muted"/> no live connection</span></div></section>
      <section className="bottom-grid"><section className="panel queue"><PanelHeading icon={<Boxes size={16}/>} title="Job queue" meta="synchronized with run"/>{state.jobs.map(j => <div className="queue-row" key={j.id}><span className={`queue-status ${j.status.toLowerCase()}`}/><div><b>{j.title}</b><small>{j.owner} · priority {j.priority}</small></div><span className="queue-label">{j.status}</span></div>)}</section><section className="panel decision"><PanelHeading icon={<ShieldCheck size={16}/>} title="Final decision" meta="auditable output"/><div className={`decision-card ${state.decision.outcome.toLowerCase()}`}><div className="decision-outcome"><span>{state.decision.outcome}</span><strong>{state.decision.confidence}%</strong></div><div className="decision-columns"><div><label>RATIONALE</label>{state.decision.rationale.map(r => <p key={r}>› {r}</p>)}</div><div><label>EVIDENCE</label>{state.decision.evidence.map(r => <p key={r}>↗ {r}</p>)}</div></div></div></section><section className="panel artifacts"><PanelHeading icon={<Archive size={16}/>} title="Artifacts" meta="run outputs"/>{state.artifacts.map(a => <div className="artifact" key={a.id}><div className="artifact-icon"><Archive size={14}/></div><div><b>{a.name}</b><small>{a.type} · {a.owner}</small></div><span className={a.status.toLowerCase()}>{a.status}</span></div>)}</section></section>
      <footer>WAWA AGENTIC TRADING STATION <span>·</span> ALL NON-LIVE VALUES ARE MARKED SIMULATION <span>·</span> BUILD 2026.08</footer>
    </main></div>
}
function Stat({ label, value, hint, tone }: { label: string; value: string; hint: string; tone: string }) { return <div className="stat"><label>{label}</label><strong className={tone}>{value}</strong><small>{hint}</small></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div><label>{label}</label><strong>{value}</strong></div> }
function PanelHeading({ icon, title, meta }: { icon: React.ReactNode; title: string; meta: string }) { return <div className="panel-heading"><div className="panel-title">{icon}<h2>{title}</h2></div><span>{meta}</span></div> }
function Empty({ text }: { text: string }) { return <div className="empty"><Search size={18}/>{text}</div> }
function AgentCard({ agent }: { agent: Agent }) { const tone = statusTone[agent.status]; return <article className={`agent-card ${tone}`} style={{ '--agent-color': agent.color } as React.CSSProperties}><div className="agent-top"><div className="agent-avatar" aria-hidden="true"><span/><span/><span/></div><div className="agent-identity"><div><strong>{agent.name}</strong><span className="status-label">{agent.status.replace('_', ' ')}</span></div><small>{teamMeta[agent.team].label} · {agent.role}</small></div><div className="activity-bars" aria-label={`${agent.status} activity`}><i/><i/><i/><i/></div></div><div className="agent-task"><div className="task-meta"><span>CURRENT TASK</span><b>{agent.task.progress}%</b></div><strong>{agent.task.title}</strong><div className="progress"><i style={{ width: `${agent.task.progress}%` }}/></div><div className="task-details"><span><Terminal size={11}/> {agent.task.tool}</span><span>{agent.task.elapsed}</span></div></div><div className="agent-output"><label>LAST OUTPUT</label><p>{agent.lastOutput}</p></div>{agent.task.dependency && <div className="dependency"><LockKeyhole size={11}/> DEPENDS ON: {agent.task.dependency}</div>}</article> }
export default App
